"""second migration

Revision ID: 5df34eea97dd
Revises: 02ed04fa2031
Create Date: 2023-07-08 17:16:20.397742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5df34eea97dd'
down_revision = '02ed04fa2031'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
